import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/app/providers';
import Navbar from '@/components/navbar/navbar';
import { PropsWithChildren } from 'react';
import { getJwtTokenAction } from '@/auth/actions/get-jwt-token-action';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: PropsWithChildren) {
	return (
		<html
			lang='en'
			className='white'>
			<body className={inter.className}>
				<Providers decodedJwtPayload={await getJwtTokenAction()}>
					<Navbar
						isAuthenticated={(await getJwtTokenAction()) ? true : false}
					/>
					{children}
				</Providers>
			</body>
		</html>
	);
}
