import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/app/providers';
import Navbar from '@/components/navbar/navbar';
import { PropsWithChildren } from 'react';
import { cookies } from 'next/headers';
import jwt from 'jsonwebtoken';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	// Returns decoded authentication token
	function getAuthToken() {
		const jwtToken = cookies().get('token');
		return jwt.decode(jwtToken?.value as string);
	}

	return (
		<html
			lang='en'
			className='white'>
			<body className={inter.className}>
				<Providers>
					<Navbar jwtToken={getAuthToken()} />
					{children}
				</Providers>
			</body>
		</html>
	);
}
